# Generated by Django 6.1 on 2026-08-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The (rewritten, satirical) article body')),
                ('event_date', models.DateField(help_text='When the real-world event actually happened')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True, help_text='Original source article, for reference/attribution')),
                ('is_headline', models.BooleanField(default=False, help_text='Pin this as the big top story')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
