# Generated by Django 6.1 on 2026-08-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_mode', models.CharField(choices=[('server', 'Server-KI (automatisch)'), ('local', 'Lokale Prüfung (manuell im Admin)')], default='server', max_length=10)),
            ],
            options={
                'verbose_name': 'Site-Einstellung',
                'verbose_name_plural': 'Site-Einstellungen',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='ai_processed',
            field=models.BooleanField(default=False, help_text='Has this gone through the satire rewrite yet? Unprocessed articles are hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from the source API, used to avoid fetching the same item twice', max_length=100, null=True, unique=True),
        ),
    ]
