# Generated by Django 6.1 on 2026-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitesettings_article_ai_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.CharField(blank=True, help_text='shot preview text for home article', max_length=100),
        ),
    ]
