# Generated by Django 6.1 on 2026-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin',
            field=models.CharField(choices=[('ai', 'KI-generiert'), ('human', 'Redaktion'), ('user', 'Nutzer-generiert')], default='ai', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.CharField(blank=True, help_text='Short teaser for the homepage. Leave blank to auto-generate one from `text`.', max_length=300),
        ),
    ]
