# Generated by Django 6.1 on 2026-08-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_article_origin_alter_article_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.CharField(blank=True, help_text='Short preview text for the home page article. Leave blank to auto-generate one from `text`.', max_length=100),
        ),
    ]
